/-
Copyright (c) 2026 Prob27b formalization. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Prob27b formalization
-/
import Prob27b.Proofs.RingModel.Basic

/-!
# Keystone: `A = R[π]` is a finite, torsion-free, free `D = 𝔽₂[π]`-algebra

`D = 𝔽₂[π]` is a PID. Here we certify Problem 27's structural hypotheses on `A`:
`D ↪ A` (`algDA_injective`), torsion-freeness (`instNoZeroSMulDivisorsDA`), and
finiteness (`instModuleFiniteDA`). Over the PID `D` these give `Module.Free D A`
(hence `Module.Flat D A`) by Mathlib's structure theorem — the input to
`A ↪ B = K ⊗_D A` being injective.
-/

namespace Prob27b

open Polynomial

instance : Fact (Nat.Prime 2) := ⟨by norm_num⟩

theorem algebraMap_D_A_eq : (algebraMap D A) = algDA := rfl

/-- `D ↪ A` (Problem 27's `D ⊆ A`): the structure map is injective. -/
theorem algDA_injective : Function.Injective (algebraMap D A) := by
  rw [algebraMap_D_A_eq, algDA]
  exact Polynomial.map_injective _ (FaithfulSMul.algebraMap_injective (ZMod 2) R)

/-- Every nonzero polynomial over the field `𝔽₂` is monic (its leading coefficient,
being nonzero in `ZMod 2`, is `1`). -/
theorem D_monic_of_ne_zero {d : D} (hd : d ≠ 0) : d.Monic := by
  have h0 : d.leadingCoeff ≠ 0 := Polynomial.leadingCoeff_ne_zero.mpr hd
  unfold Polynomial.Monic
  revert h0; generalize d.leadingCoeff = x; revert x; decide

/-- `A` is torsion-free over `D`: if `d ≠ 0` then multiplication by `algDA d`
(a monic, hence regular, polynomial) is injective. -/
instance instNoZeroSMulDivisorsDA : NoZeroSMulDivisors D A := by
  refine ⟨fun {d a} h => ?_⟩
  rcases eq_or_ne d 0 with hd | hd
  · exact Or.inl hd
  · refine Or.inr ?_
    rw [Algebra.smul_def, algebraMap_D_A_eq] at h
    have hm : (algDA d).Monic := by
      have := (D_monic_of_ne_zero hd).map (algebraMap (ZMod 2) R)
      simpa [algDA] using this
    exact hm.isRegular.left (by simpa using h)

/-- `monomial n r = (X^n : D) • C r` in `A` (the `D`-module structure). -/
theorem monomial_eq_smul (n : ℕ) (r : R) : (monomial n r : A) = (X ^ n : D) • (C r : A) := by
  rw [Algebra.smul_def, algebraMap_D_A_eq, algDA]
  simp [Polynomial.map_pow, C_mul_X_pow_eq_monomial]

/-- `algebraMap 𝔽₂ A c = C (algebraMap 𝔽₂ R c)` (the `𝔽₂`-algebra structure on
`A = R[π]` is "constant of the scalar"). Proved via `c • 1` to dodge the
noncommutativity of `R`. -/
theorem algebraMap_ZMod2_A (c : ZMod 2) :
    algebraMap (ZMod 2) A c = C (algebraMap (ZMod 2) R c) := by
  rw [Algebra.algebraMap_eq_smul_one, ← map_one (C : R →+* A), Polynomial.smul_C,
    ← Algebra.algebraMap_eq_smul_one]

/-- The scalar tower `𝔽₂ → D → A`. -/
instance instIsScalarTowerZDA : IsScalarTower (ZMod 2) D A :=
  IsScalarTower.of_algebraMap_eq fun c => by
    rw [algebraMap_ZMod2_A, algebraMap_D_A_eq, Polynomial.algebraMap_eq, algDA,
      Polynomial.coe_mapRingHom, Polynomial.map_C]

/-- `A = R[π]` is finite as a `D = 𝔽₂[π]`-module, generated by the eight basis
elements `{C e, …, C w}` of `R` (viewed as constants). Each `C r` is an
`𝔽₂`-combination of these (`Polynomial.smul_C`), hence a `D`-combination via the
tower `𝔽₂ → D → A`; and `monomial n r = X^n • C r`. -/
instance instModuleFiniteDA : Module.Finite D A := by
  rw [Module.finite_def, Submodule.fg_def]
  refine ⟨(fun r : R => (C r : A)) '' {e, f, u, v, p, q, s, w},
    Set.Finite.image _ (Set.toFinite _), ?_⟩
  rw [Submodule.eq_top_iff']
  intro a
  induction a using Polynomial.induction_on' with
  | add P Q hP hQ => exact Submodule.add_mem _ hP hQ
  | monomial n r =>
    rw [monomial_eq_smul]
    refine Submodule.smul_mem _ _ ?_
    obtain ⟨α, β, γ, δ, η, θ, ι, κ, rfl⟩ := R_generic r
    have mem : ∀ b : R, b ∈ ({e, f, u, v, p, q, s, w} : Set R) →
        (C b : A) ∈ Submodule.span D ((fun r : R => (C r : A)) '' {e, f, u, v, p, q, s, w}) :=
      fun b hb => Submodule.subset_span ⟨b, hb, rfl⟩
    simp only [map_add, ← Polynomial.smul_C]
    refine Submodule.add_mem _ (Submodule.add_mem _ (Submodule.add_mem _ (Submodule.add_mem _
      (Submodule.add_mem _ (Submodule.add_mem _ (Submodule.add_mem _ ?_ ?_) ?_) ?_) ?_) ?_) ?_) ?_
    · exact Submodule.smul_of_tower_mem _ _ (mem e (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem f (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem u (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem v (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem p (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem q (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem s (by simp))
    · exact Submodule.smul_of_tower_mem _ _ (mem w (by simp))

/-- `A` is torsion-free over the domain `D`: multiplication by a regular (nonzero)
`r : D` is injective on `A` (from `NoZeroSMulDivisors`). -/
instance instTorsionFreeDA : Module.IsTorsionFree D A where
  isSMulRegular r hr := by
    have hr0 : r ≠ 0 := isRegular_iff_ne_zero.mp hr
    intro m₁ m₂ hm
    have hm' : r • m₁ = r • m₂ := hm
    have hz : r • (m₁ - m₂) = (0 : A) := by rw [smul_sub r m₁ m₂, hm', sub_self]
    exact sub_eq_zero.mp ((eq_zero_or_eq_zero_of_smul_eq_zero hz).resolve_left hr0)

/-- `A` is **free** over the PID `D` (finite + torsion-free over a principal ideal
domain). The `have … ; exact` bridges a defeq instance-diamond between `A`'s
`Ring`- and `Semiring`-derived additive structures. -/
noncomputable instance instFreeDA : Module.Free D A := by
  have h := Module.free_of_finite_type_torsion_free' (R := D) (M := A)
  exact h

/-- **`A ↪ B = K ⊗_D A` is injective.** From `A` flat over `D` (free ⇒ flat) and
`D ↪ K` injective (`IsFractionRing`). This is the key input letting the
`Int(A)` witnesses transfer faithfully (value `∈ A ⇔ π`-divisible). -/
theorem incA_injective : Function.Injective (incA : A →ₐ[D] B) :=
  Algebra.TensorProduct.includeRight_injective (IsFractionRing.injective D K)

end Prob27b
