import Prob20.Defs
import Prob20.Theorems
import Prob20.Proofs.Domain.Basic
import Prob20.Proofs.KeyObs.Basic
import Prob20.Proofs.Injective.Basic
import Prob20.Proofs.Surjective.Basic
import Prob20.Proofs.Headline.Basic
import Prob20.Solution
import Prob20.Discharge
