/-
Copyright (c) 2026 Prob27b formalization. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Prob27b formalization
-/
import Mathlib

/-!
# Definitions for the Problem 27(b) counterexample (FROZEN)

This file is **frozen** after the SETUP stage: every object needed to *state* the
four theorems of `Theorems.lean` lives here, and nothing in this file may change
during the proving phase. All later work goes in `Prob27b/Proofs/`.

The base ring `R` is the truncated path algebra over `𝔽₂ = ZMod 2` of the quiver

  e --u--> f --v--> e   (all paths of length ≥ 4 are zero),

with `𝔽₂`-basis `e, f, u, v, p = uv, q = vu, s = uvu, w = vuv` (dimension 8).
We realize `R` via its **left regular representation** on the 8-dimensional path
space, basis ordered `0:e 1:f 2:u 3:v 4:p 5:q 6:s 7:w`. Each path `g` becomes the
`8×8` matrix `L_g` over `𝔽₂` of "left multiply by `g`"; associativity and the ring
axioms are then inherited from the matrix algebra (this is the point of the
matrix model — associativity is never proved by hand).
-/

namespace Prob27b

open Matrix Polynomial

/-- The ambient matrix algebra `M₈(𝔽₂)`. -/
abbrev Mat : Type := Matrix (Fin 8) (Fin 8) (ZMod 2)

/-! ## The four generator matrices (left regular representation)

Entry `(i, j) = 1` of `L_g` means `basisᵢ = g · basisⱼ`. -/

/-- `L_e`: vertex idempotent at `e` (fixes `e, u, p, s`; kills the rest). -/
def mE : Mat :=
  single 0 0 1 + single 2 2 1 + single 4 4 1 + single 6 6 1

/-- `L_f`: vertex idempotent at `f` (fixes `f, v, q, w`; kills the rest). -/
def mF : Mat :=
  single 1 1 1 + single 3 3 1 + single 5 5 1 + single 7 7 1

/-- `L_u`: the arrow `u : e → f` (`f ↦ u`, `v ↦ p`, `q ↦ s`). -/
def mU : Mat :=
  single 2 1 1 + single 4 3 1 + single 6 5 1

/-- `L_v`: the arrow `v : f → e` (`e ↦ v`, `u ↦ q`, `p ↦ w`). -/
def mV : Mat :=
  single 3 0 1 + single 5 2 1 + single 7 4 1

/-- The base ring `R`: the `𝔽₂`-subalgebra of `M₈(𝔽₂)` generated by the four path
generators. Associativity etc. are inherited from `Mat`. -/
def R : Subalgebra (ZMod 2) Mat := Algebra.adjoin (ZMod 2) {mE, mF, mU, mV}

theorem mE_mem : mE ∈ R := Algebra.subset_adjoin (by simp)
theorem mF_mem : mF ∈ R := Algebra.subset_adjoin (by simp)
theorem mU_mem : mU ∈ R := Algebra.subset_adjoin (by simp)
theorem mV_mem : mV ∈ R := Algebra.subset_adjoin (by simp)

/-! ## The eight basis elements of `R`

The four generators (with their membership proofs) and the four nontrivial paths
`p, q, s, w` (as products inside the subalgebra). -/

def e : R := ⟨mE, mE_mem⟩
def f : R := ⟨mF, mF_mem⟩
def u : R := ⟨mU, mU_mem⟩
def v : R := ⟨mV, mV_mem⟩
def p : R := u * v
def q : R := v * u
def s : R := u * v * u
def w : R := v * u * v

/-- The evaluation point `a₀ = u + v` witnessing that `F · e` is not null. -/
def a₀ : R := u + v

/-! ## Polynomials, evaluation, and the lift

`evalR r F = Σᵢ Fᵢ · rⁱ` substitutes the ring element `r` for the evaluation
variable, keeping coefficients on the **left** and assuming **no** commutativity
(`R` is genuinely noncommutative: `u * v = p ≠ q = v * u`). -/

/-- Left-coefficient evaluation `Σᵢ pᵢ · rⁱ` of a polynomial over `R` at `r : R`. -/
noncomputable def evalR (r : R) (poly : Polynomial R) : R :=
  poly.eval₂ (RingHom.id R) r

/-- The null polynomial `F(X) = u X² + e X³ + (e+u) X⁴ + e X⁵ + e X⁶`. The
indeterminate is the evaluation variable; the coefficients are constants in `R`.
Right multiplication by the constant `e` (the right-ideal test) is `F * C e`. -/
noncomputable def F : Polynomial R :=
  C u * X ^ 2 + C e * X ^ 3 + C (e + u) * X ^ 4 + C e * X ^ 5 + C e * X ^ 6

/-- `A = R[π]`, with the central indeterminate `π := (X : A)` playing the role of
`D = 𝔽₂[π]`. Concretely `A = Polynomial R` and `A / π·A ≅ R`. -/
abbrev A : Type := Polynomial R

/-- `Ftilde` is `F` with its coefficients pushed into `A` via the constant
embedding `C : R →+* A`; it lives in `Polynomial A` (evaluation variable `Y`,
coefficients constant in `π`). `P := Ftilde / π` is the integer-valued polynomial. -/
noncomputable def Ftilde : Polynomial A := F.map (C : R →+* A)

/-! ## Problem 27's setup: `D = 𝔽₂[π]`, `K = Frac(D)`, `B = K ⊗_D A`, and `Int(A)`

Problem 27 takes a torsion-free finite `D`-algebra `A` (here `A = R[π]`, with
`D = 𝔽₂[π] ⊆ A`), forms `K = Frac(D)` and the coefficient ring `B = K ⊗_D A`, and
defines `Int(A) = { f ∈ B[X] : f(A) ⊆ A }`. We build all of this *literally*: the
`D`-algebra structure on `A` (`π ↦ π`, `𝔽₂ ↦ R`), the tensor product `B`, and the
canonical embedding `A ↪ B`. -/

/-- `D = 𝔽₂[π]`, the base domain of Problem 27. -/
abbrev D : Type := Polynomial (ZMod 2)

/-- The `D`-algebra structure map on `A = R[π]`: apply the unit `𝔽₂ → R` to
coefficients (`π ↦ π`). -/
noncomputable def algDA : D →+* A := Polynomial.mapRingHom (algebraMap (ZMod 2) R)

/-- The image of `D` is central in `A` (coefficients come from the central `𝔽₂`,
`π` is central), so `algDA` makes `A` a `D`-algebra. -/
theorem algDA_central (d : D) (x : A) : algDA d * x = x * algDA d := by
  refine Polynomial.ext fun n => ?_
  simp only [algDA, Polynomial.coe_mapRingHom]
  rw [coeff_mul, ← Finset.Nat.sum_antidiagonal_swap, coeff_mul]
  simp [coeff_map, Algebra.commutes]

/-- `A = R[π]` is a `D = 𝔽₂[π]`-algebra. -/
noncomputable instance instAlgebraDA : Algebra D A := algDA.toAlgebra' algDA_central

/-- `K = Frac(𝔽₂[π]) = 𝔽₂(π)`, the fraction field of `D`. -/
abbrev K : Type := FractionRing D

/-- `B = K ⊗_D A`, Problem 27's coefficient ring for `Int(A)`. -/
abbrev B : Type := TensorProduct D K A

/-- The canonical embedding `A ↪ B`, `a ↦ 1 ⊗ a`. (Injective — proved in
`Proofs/Lift`.) -/
noncomputable def incA : A →ₐ[D] B := Algebra.TensorProduct.includeRight

/-- The canonical map `K → B`, `k ↦ k ⊗ 1`. -/
noncomputable def incK : K →+* B := Algebra.TensorProduct.includeLeftRingHom

/-- `π⁻¹ ∈ B`: the inverse of the image of `π`, which exists because `π ≠ 0` in the
domain `D` is invertible in `K = Frac(D)`. -/
noncomputable def πBinv : B := incK (algebraMap D K (X : D))⁻¹

/-- `P = F̃ / π ∈ B[X]`, the integer-valued polynomial of SKETCH Step 4. -/
noncomputable def Pb : Polynomial B := Polynomial.C πBinv * Ftilde.map (incA : A →+* B)

/-- The constant polynomial `e ∈ A ⊆ B`. The product `Pb · econstB` is what must
escape `Int(A)`. -/
noncomputable def econstB : Polynomial B := Polynomial.C (incA (C e))

/-- `g ∈ B[X]` is **integer-valued on `A`** (Problem 27's `Int(A)` membership):
`g(a) ∈ A` for every `a ∈ A`, identifying `A` with its image in `B`. -/
def IntegerValued (g : Polynomial B) : Prop := ∀ a : A, g.eval (incA a) ∈ Set.range incA

/-- `Int(A) = { f ∈ B[X] : f(A) ⊆ A }` (Problem 27). The conjecture claims this is
a ring; in particular it should be closed under multiplication. -/
def IntA : Set (Polynomial B) := {g | IntegerValued g}

end Prob27b
